from ctypes import *
from ctypes.wintypes import *

INT = c_int
USHORT = c_ushort

LPVOID = c_void_p
LPCVOID = c_void_p

LPBYTE = POINTER(BYTE)
LPWORD = POINTER(WORD)
LPDWORD = POINTER(DWORD)
PLONG = POINTER(c_long)

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ACCESS_MASK = DWORD

PHKEY = POINTER(HKEY)
PFILETIME = c_void_p
LPFILETIME = PFILETIME

LPSECURITY_ATTRIBUTES = LPVOID
LPOVERLAPPED = LPVOID
LPSTARTUPINFO = LPVOID
LPPROCESS_INFORMATION = LPVOID
LPSYSTEM_INFO = LPVOID
LPMEMORYSTATUS = LPVOID

REGSAM = ACCESS_MASK
